name: Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build ExampleProvider
        run: ./gradlew ExampleProvider:make

      - name: Locate .cs3
        run: |
          echo "Searching for .cs3 files..."
          find . -type f -name "*.cs3" -print

      - name: Upload artifacts (.cs3)
        uses: actions/upload-artifact@v4
        with:
          name: cs3
          path: "**/*.cs3"
          if-no-files-found: error
