name: Build

on:
  push:
    branches: [ "master" ]   # ta branche par défaut, chez toi c’est master
  workflow_dispatch:         # ajoute le bouton "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build ExampleProvider
        run: ./gradlew ExampleProvider:make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cs3
          path: "**/build/outputs/*.cs3"
